[workspace]

members = [
    "chapter02",
    "chapter03",
    "chapter04",
    "chapter05",
    "chapter06",
    "chapter07",
    "chapter08",
    "homework/convert_celsius_to_fahrenheit",
    "homework/fibonacci"
]
