name: Cpp

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  linux:
    # TODO use ubuntu-latest
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        config:
          - { cc: "gcc-10", cxx: "g++-10" }
          - { cc: "clang-10", cxx: "clang++-10" }

    steps:
      - uses: actions/checkout@v2

      - name: Install GCC
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/ppa
          sudo apt update
          sudo apt install gcc-10 g++-10

      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache@v2
        with:
          path: dependencies
          key: ${{ runner.os }}-gcc10-dependencies-20201006

      - name: Build and install dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: sudo bash -e ./cpp/scripts/build-install-dependencies.sh

      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit == 'true'
        run: sudo bash -e ./cpp/scripts/install-dependencies.sh

      - name: Configure
        run: cd cpp ; cmake -S . -B build
        env:
          CC: ${{ matrix.config.cc }}
          CXX: ${{ matrix.config.cxx }}

      - name: Build
        run: cd cpp ; cmake --build build --config Release -j$(nproc)
# TODO macos
