name: ArchLinux

on: [push, pull_request]

jobs:
  cpp:
    runs-on: ubuntu-latest
    container: archlinux
    strategy:
      matrix:
        compiler: [g++, clang++]

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel clang lld llvm cmake wget unzip intel-tbb \
          asio benchmark boost fmt gtest icu nlohmann-json protobuf zstd
          wget https://github.com/Neargye/magic_enum/archive/v0.6.6.zip
          unzip v0.6.6.zip
          cd magic_enum-0.6.6
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release -j$(nproc)
          cmake --build build --config Release --target install
          wget https://github.com/gabime/spdlog/archive/v1.8.0.zip
          unzip v1.8.0.zip
          cd spdlog-1.8.0
          cmake -S . -B build -DSPDLOG_FMT_EXTERNAL_HO=ON
          cmake --build build --config Release -j$(nproc)
          cmake --build build --config Release --target install
          wget https://github.com/facebook/rocksdb/archive/v6.11.4.zip
          unzip v6.11.4.zip
          cmake -DCMAKE_BUILD_TYPE=Release \
          -DWITH_BZ2=OFF -DWITH_LZ4=OFF -DWITH_SNAPPY=OFF -DWITH_ZLIB=OFF -DWITH_ZSTD=ON \
          -DUSE_RTTI=ON -DWITH_JEMALLOC=OFF -DWITH_GFLAGS=OFF -DFAIL_ON_WARNINGS=OFF -DPORTABLE=ON \
          -DWITH_BENCHMARK_TOOLS=OFF -S . -B build
          cmake --build build --config Release -j$(nproc)
          cmake --build build --config Release --target install

      - name: Configure
        run: cd cpp ; cmake -S . -B build
        env:
          CXX: ${{ matrix.compiler }}

      - name: Build
        run: cd cpp ; cmake --build build --config Release -j$(nproc)

  rust:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: cd rust ; cargo build
