name: macOS

on: [push, pull_request]

jobs:
  cpp:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: |
          brew update
          brew install asio google-benchmark boost fmt nlohmann-json protobuf
          wget https://github.com/google/googletest/archive/release-1.10.0.zip
          unzip release-1.10.0.zip
          cd googletest-release-1.10.0
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release -j`sysctl -n hw.ncpu`
          sudo cmake --build build --config Release --target install
          wget https://github.com/Neargye/magic_enum/archive/v0.6.6.zip
          unzip v0.6.6.zip
          cd magic_enum-0.6.6
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release -j`sysctl -n hw.ncpu`
          cmake --build build --config Release --target install
          wget https://github.com/gabime/spdlog/archive/v1.8.0.zip
          unzip v1.8.0.zip
          cd spdlog-1.8.0
          cmake -S . -B build -DSPDLOG_FMT_EXTERNAL_HO=ON
          cmake --build build --config Release -j`sysctl -n hw.ncpu`
          cmake --build build --config Release --target install
          wget https://github.com/facebook/rocksdb/archive/v6.11.4.zip
          unzip v6.11.4.zip
          cd rocksdb-6.11.4
          cmake -DCMAKE_BUILD_TYPE=Release \
          -DWITH_BZ2=OFF -DWITH_LZ4=OFF -DWITH_SNAPPY=OFF -DWITH_ZLIB=OFF -DWITH_ZSTD=ON \
          -DUSE_RTTI=ON -DWITH_JEMALLOC=OFF -DWITH_GFLAGS=OFF -DFAIL_ON_WARNINGS=OFF -DPORTABLE=ON \
          -DWITH_BENCHMARK_TOOLS=OFF -S . -B build
          cmake --build build --config Release -j`sysctl -n hw.ncpu`
          cmake --build build --config Release --target install

      - name: Configure
        run: cd cpp ; cmake -S . -B build

      - name: Build
        run: cd cpp ; cmake --build build --config Release -j`sysctl -n hw.ncpu`
        env:
          C_INCLUDE_PATH: /usr/local/include
          CPLUS_INCLUDE_PATH: /usr/local/include

  rust:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: cd rust ; cargo build
