name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: archlinux
    strategy:
      matrix:
        compiler: [g++, clang++]

    steps:
    - uses: actions/checkout@v2

    - name: install
      run: |
        pacman -Syu --noconfirm
        pacman -S --noconfirm base-devel clang lld llvm cmake wget unzip git \
        intel-tbb boost fmt nlohmann-json gtest curl
        wget https://github.com/Neargye/magic_enum/archive/v0.6.5.zip
        unzip v0.6.5.zip
        cd magic_enum-0.6.5
        mkdir build && cd build && cmake ..
        cmake --build . -j4
        make install
        git clone https://github.com/linux-test-project/lcov
        cd lcov
        make install
        wget http://search.cpan.org/CPAN/authors/id/N/NW/NWCLARK/PerlIO-gzip-0.20.tar.gz
        tar -xzvf PerlIO-gzip-0.20.tar.gz
        cd PerlIO-gzip-0.20
        perl Makefile.PL
        make -j4 && make install
        wget http://www.cpan.org/authors/id/M/MA/MAKAMAKA/JSON-2.90.tar.gz
        tar -xzvf JSON-2.90.tar.gz
        cd JSON-2.90
        perl Makefile.PL
        make -j4 && make install
        curl '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

    - name: configure-cpp
      env:
        CXX: ${{ matrix.compiler }}
      run: cd Cpp && mkdir build && cd build && cmake ..

    - name: build-cpp
      run: cd Cpp && cmake --build build -j4 --target all

    - name: build-rust
      run: cd Rust && cargo build
