name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cpp:

    runs-on: ubuntu-latest
    container: archlinux
    strategy:
      matrix:
        compiler: [g++, clang++]

    steps:
    - uses: actions/checkout@v2

    - name: install
      run: |
        pacman -Syu --noconfirm
        pacman -S --noconfirm base-devel clang lld cmake wget unzip git \
        intel-tbb boost fmt nlohmann-json gtest
        wget https://github.com/Neargye/magic_enum/archive/v0.6.5.zip
        unzip v0.6.5.zip
        cd magic_enum-0.6.5
        mkdir build && cd build && cmake ..
        cmake --build . -j4
        make install
        git clone https://github.com/tanakh/cmdline
        cd cmdline
        cp cmdline.h /usr/local/include

    - name: configure
      env:
        CXX: ${{ matrix.compiler }}
      run: cd Cpp && mkdir build && cd build && cmake -DCLANG_TIDY=TRUE ..

    - name: build
      run: cd Cpp && cmake --build build -j4 --target all

  rust:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2

    - name: build
      run: cd Rust && cargo build
