name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  cpp:
    runs-on: ubuntu-latest
    container: archlinux
    strategy:
      matrix:
        compiler: [g++, clang++]

    steps:
      - uses: actions/checkout@v2

      - name: Install libraries and tools
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel clang lld llvm cmake wget unzip git \
          intel-tbb boost fmt nlohmann-json gtest spdlog rocksdb protobuf
          wget https://github.com/Neargye/magic_enum/archive/v0.6.6.zip
          unzip v0.6.6.zip
          cd magic_enum-0.6.6
          mkdir build && cd build && cmake ..
          cmake --build . -j4
          make install

      - name: CMake
        env:
          CXX: ${{ matrix.compiler }}
        run: cd cpp && mkdir build && cd build && cmake -DCLANG_TIDY=TRUE ..

      - name: Build
        run: cd cpp && cmake --build build -j4 --target all

  rust:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2

      - name: build
        run: cd rust && cargo build
