name: Rust

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: cd rust ; cargo build --release
